import { ElementRef, OnInit } from '@angular/core';
import { Country } from '../../interface/country.interface';
import { ControlValueAccessor } from '@angular/forms';
import { CountryCode } from '../../interface/country-code.interface';
import { CountryService } from '../../service/country.service';
import { LocaleService } from '../../service/locale.service';
export declare class IntPhonePrefixComponent implements OnInit, ControlValueAccessor {
    private service;
    private localeService;
    locale: string;
    defaultCountry: string;
    maxLength: number;
    onlyNumbers: boolean;
    phoneComponent: ElementRef;
    onTouch: Function;
    onModelChange: Function;
    countries: Country[];
    locales: CountryCode;
    selectedCountry: Country;
    countryFilter: string;
    showDropdown: boolean;
    phoneInput: string;
    disabled: boolean;
    value: string;
    handleKeyboardEvent(event: KeyboardEvent): void;
    constructor(service: CountryService, localeService: LocaleService, phoneComponent: ElementRef);
    ngOnInit(): void;
    setDisabledState(isDisabled: boolean): void;
    registerOnTouched(fn: Function): void;
    registerOnChange(fn: Function): void;
    writeValue(value: string): void;
    updateSelectedCountry(event: Event, countryCode: string): void;
    showDropDown(): void;
    hideDropdown(event: Event): void;
    updatePhone(): void;
    private translateCountryNames();
    private orderCountriesByName();
    private updatePhoneInput(countryCode);
    private findPrefix(prefix);
    private updateValue();
    private static startsWithPlus(text);
    private static reducePrefixes(foundPrefixes);
}
